#!/bin/zsh
project='pkgbuilder'
projectc='PKGBUILDer'

xgettext -c ./$project/*.py INSTALL.py localeprovider.py -o ./messages.pot

sed '1,+17d' ./messages.pot > ./messages.pot.tmp

pot='# '$projectc' pot file.
# Copyright © 2011-2013, Kwpolska.
# This file is distributed under the same license as the '$projectc' package.
# Kwpolska <kwpolska@kwpolska.tk>, 2011-2013.
#
msgid ""
msgstr ""
"Project-Id-Version: #version\\n"
"Report-Msgid-Bugs-To: Kwpolska <kwpolska@kwpolska.tk>\\n"
"POT-Creation-Date: #datel\\n"
"PO-Revision-Date: #datel\\n"
"Last-Translator: Kwpolska <kwpolska@kwpolska.tk>\\n"
"Language-Team: Kwpolska <kwpolska@kwpolska.tk>\\n"
"Language: en\\n"
"MIME-Version: 1.0\\n"
"Content-Type: text/plain; charset=UTF-8\\n"
"Content-Transfer-Encoding: 8bit\\n"'

echo $pot > messages.pot
cat ./messages.pot.tmp >> messages.pot
rm ./messages.pot.tmp

sed "s/#version/$version/g" messages.pot -i
sed "s/#datel/$datel/g" messages.pot -i

for i in ./locale/*; do
    language=$(basename $i)

    podir="./locale/$language/LC_MESSAGES"
    popath="./locale/$language/LC_MESSAGES/$project.po"
    sed 's/\"Project-Id-Version: .*/\"Project-Id-Version: '$version'\\n\"/' $popath -i
    msgmerge $popath messages.pot -o $popath
    fuzzy=$(cat $popath | grep -c '#, fuzzy')
    empty=$(cat $popath | pcregrep -cM 'msgstr ""\n$')
    if [ $fuzzy != '0' ]; then
        echo "WARNING: $fuzzy fuzzy strings in language $language."
    fi

    if [ $empty != '0' ]; then
        echo "WARNING: $empty empty strings in language $language."
    fi

    msgfmt -o $podir/$project.mo $popath
done
