#!/bin/zsh
project="pkgbuilder"
projectc="PKGBUILDer"
aurcat="system"

version=$1
if [[ $version = '' ]]; then
    echo 'Version number?'
    echo -n '> '
    read version
fi

rm -rf $project.egg-info __pycache__ $project/__pycache__ dist build

date=$(date '+%Y-%m-%d')
datel=$(date '+%Y-%m-%d %H:%M%z')
datep=$(date '+%Y%m%d')

sed "s/version=.*/version='$version',/g" setup.py -i
sed "s/release = .*/release = '$version'/g" docs/conf.py -i
sed "s/:Version: .*/:Version: $version/g" docs/*.rst -i
sed "s/# $projectc v.*/# $projectc v$version/" $project/*.py -i
sed "s/__version__ = .*/__version__ = '$version'/g" $project/__init__.py -i
sed "s/pkgver=.*/pkgver=$version/g" PKGBUILD -i

sed "s/pkgver=.*/pkgver=$datep/g" PKGBUILD-git -i
sed "s/:Date: .*/:Date: $date/g" docs/*.rst -i

cp docs/README.rst docs/CHANGELOG.rst docs/CONTRIBUTING.rst .
cp docs/README.rst README

rm docs/$project.8.gz | true
rst2man docs/$project.rst > docs/$project.8
gzip docs/$project.8

rm docs/pb.8.gz | true
rst2man docs/pb.rst > docs/pb.8
gzip docs/pb.8

./localegen

# pbwrapper help testing
pacman -Sh > /tmp/pbwrapperhelp
bin/$project -h >> /tmp/pbwrapperhelp

diff -u .pbwrapperhelp /tmp/pbwrapperhelp > /tmp/pbwrapperdiff
if [[ $? = 1 ]]; then
    echo 'pbwrapperhelp has changed.'
    cat /tmp/pbwrapperdiff
    echo 'Hit Enter to quit or c to copy the file over and continue.'
    read pbwrapperhelp
    if [[ $pbwrapperhelp = 'c' ]]; then
        cp /tmp/pbwrapperhelp .pbwrapperhelp
        rm /tmp/pbwrapperhelp /tmp/pbwrapperdiff
        echo 'Continuing with release scripts.'
    else
        rm /tmp/pbwrapperhelp /tmp/pbwrapperdiff
        exit 1
    fi
fi

python -c "import $project"
if [[ $? = 1 ]]; then
    echo "Import failed.  Fix your code or don't come back."
    exit 1
fi

./tests.py
if [[ $? = 1 ]]; then
    echo "Tests failed.  Fix your code or don't come back."
    exit 1
fi

echo 'This is the last chance to quit.  Hit ^C now if you want to.'
read bailout

./setup.py sdist upload

###: AUR Package Creation
md5out=$(md5sum 'dist/'$project'-'$version'.tar.gz'|awk '{print $1}')
sed "s/md5sums=.*/md5sums=('$md5out')/" PKGBUILD -i
###: python2-$project package
#sed "s/md5sums=.*/md5sums=('$md5out')/" PKGBUILD-2 -i

rm -rf MKPKGBUILD
mkdir MKPKGBUILD
cd MKPKGBUILD

###: $project{,-git} packages
mkdir $project{,-git}
cp ../PKGBUILD ./$project
cp ../PKGBUILD-git ./$project"-git/PKGBUILD"
tar -czvf $project"-0.1.0-1".src.tar.gz $project
tar -czvf $project"-git-19700101-1".src.tar.gz $project"-git"

###: python{2,}-$project{,-git} packages
#mkdir python{,2}'-'$project{,-git}
#cp ../PKGBUILD ./python-$project
#cp ../PKGBUILD-git ./python-$project"-git/PKGBUILD"
#cp ../PKGBUILD-2 ./python2-$project/PKGBUILD
#cp ../PKGBUILD-2-git ./python2-$project"-git/PKGBUILD"
#tar -czvf python-$project"-0.1.0-1".src.tar.gz python-$project
#tar -czvf python2-$project"-0.1.0-1".src.tar.gz python-$project
#tar -czvf python-$project"-git-19700101-1".src.tar.gz python-$project"-git"
#tar -czvf python2-$project"-git-19700101-1".src.tar.gz python-$project"-git"

aurploader -a pkgbuilder*.src.tar.gz
cd ..
rm -rf MKPKGBUILD

###: git commit
if [[ $2 != '-c' ]]; then
    echo 'Commit message (sans the version?)'
    echo -n '> '
    read commitmsg
    if [[ commitmsg = '' ]]; then
        cm='t'
    fi
else
    cm='t'
fi

rm -rf $project.egg-info __pycache__ $project/__pycache__ dist build

git add *
if [[ $? != '0' ]]; then
    echo 'Open another terminal and fix the errors.'
    read dn
    git add *
    if [[ $? != '0' ]]; then
        echo 'But please test your changes using that other terminal.'
        read dn2
        git add *
    fi
fi

if [[ $cm = 't' ]]; then
    git commit -as
else
    git commit -asm "v$version: $commitmsg"
fi

#git tag -sa "v$version" -m "Version $version"
#git push
#git push --tags
