#!/usr/bin/env python3
"""Run PKGBUILDer."""
import pkgbuilder
try:
    pkgbuilder.main_routine()
except KeyboardInterrupt:
    pkgbuilder.fancy_error('[ERR5001] KeyboardInterrupt (^C) caught.')
    exit(0)
